analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    cascade_invocations: ignore
    deprecated_member_use: ignore
    inference_failure_on_instance_creation: ignore
    library_private_types_in_public_api: ignore
    lines_longer_than_80_chars: ignore
    omit_local_variable_types: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
