name: testverygood
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.2.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  
   

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets: 
  - lib/assets/icon/
  - lib/assets/svg/
  - lib/assets/icon/active_navbar/
  - lib/assets/icon/inactive_navbar/
  - lib/assets/icon/home_icon/
  - lib/assets/icon/add_icon/

  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Bold.ttf
    - family: HappyMonkey
      fonts:
        - asset: lib/assets/fonts/HappyMonkey.ttf

